apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: 500116276682.dkr.ecr.ap-south-1.amazonaws.com/app-registry:latest
        ports:
        - containerPort: 3000


apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: myapp-container
    protocol: TCP
    nodePort: 30007
  type: NodePort